Mitrichius/hugo-theme-anubis

layouts/partials/articleInfoFull.html

Clicking the link to tag with a space would 404, this adds a hyphen which links to the correct page.

Fixed broken link on tags with spaces

---

layouts/partials/head.html

This allows end users to add additional CSS files for use in their site.
They would do this by adding
```
[params]
customCSS = [
"mycss.css"
]
```
into their config file.
This should assist with #12

Add support for custom CSS files

---

layouts/partials/footer.html

This link was getting flagged in lighthouse audits, so adding the `rel` attribute
to address it.
Used both `noopener` and `noreferrer`, since some older browsers don't support
`noopener`.

add rel attribute to address lighthouse audit issue

---

static/css/style.css

I think this minor change improves the theme when viewed on narrow screens. See linked issue for visual example. Resolves #61.

Add margin-bottom to theme-switcher.

---

assets/css/main.css

Currently, there are two rules which control the margin of the links in the navigation bar:
https://github.com/Mitrichius/hugo-theme-anubis/blob/460a61701f5edb8e8dfef63dcd25992ccd4d2e1f/assets/css/main.css#L506-L512
They treat the first link separately from the rest and then give the rest of the links asymmetric margins. This results in the links touching the edge of the grey background box for some choices of text on small screens:
You can also see that some longer links are split over two lines where it would instead make sense for them to be grouped together. This pull request symmetrizes the margins of the links and also changes their display mode to prefer grouping link text together when inserting line breaks:
However, the lack of margins on the edges of the links may have been …

Replace css rules for nav links to assist flow

---

i18n/fr.yaml

Suggestion for the french translation :
thème léger -> **thème clair**
light in english can be translated to both _léger_ (= not heavy) and _clair_ (= not dark) so it's a funny translation
passer au contenu principal -> **aller au contenu**
I think _aller au contenu_ is shorter and more used in french blogs
cf. https://www.accede-web.com/notices/fonctionnelle-graphique/recommandations-complementaires/prevoir-lapparence-des-liens-devitement/

french corrections

---

README.md
exampleSite/config.toml
exampleSiteMultilingual/config.toml
layouts/_default/single.html
layouts/partials/utterances.html

This PR adds support for the [utteran.es](https://utteranc.es/), a free and open source alternative to Disqus that stores all data in Github issues.

uteranc.es support

---

README.md
layouts/_default/rss.xml

This uses the `disable_feed` parameter from a post's frontmatter
I feel like I should mention this in the README, but I am not sure where exactly. Under the `favorite posts` section?

Allow hiding posts from RSS feed

---

README.md
layouts/partials/footer.html
layouts/partials/head.html
layouts/partials/pagination-extra.html
layouts/partials/paginationPost.html
layouts/partials/postInfo.html

1. Move the footer-extra inside the copyright diff so that there is no weird gap between the lines.
2. Add an extra to the pagination.html. This is kinda specific but allows me to include a webmention widget right before the footer.
3. Changed the post-info to include the author name and the base url for better webmention support.
4. Add the ability to set a webmention URL in the config without disrupting current config settings. See my comment [here](https://github.com/Mitrichius/hugo-theme-anubis/issues/75#issuecomment-784136709)

Footer-extra, pagination-extra, post-info, webmention-url

---

assets/css/main.css

Changing the display style to `block` removes the disclosure triangle which can make it difficult to understand that an element is a `details`. If this is an intended part of the design, feel free to reject this pull request.

Stop changing display style of summary to block

---

layouts/partials/post-info.html

This makes sure not destroying the template without setting the BaseURL

fix: put quotes around BaseUrl for author

---

layouts/partials/post-pagination.html

This PS is for the issue https://github.com/Mitrichius/hugo-theme-anubis/issues/95.
Fixing link to next/prev post in the post page by analogy with post summary ([layouts/partials/post-summary.html](https://github.com/Mitrichius/hugo-theme-anubis/blob/5dab60e04a37896c09a32137aefe821c63b3af04/layouts/partials/post-summary.html)).
This PR has been tested manually on my local development environment with the following test-cases:
* Pagination for all english posts   :heavy_check_mark:
* Pagination for all russian posts   :heavy_check_mark:

Fixing broken pagination links on the post page

---

layouts/partials/pagination.html

Hi, @Mitrichius! Here is a bug that I found.
1. Set `baseUrl` config parameter to `http://localhost/some/prefix/`
2. Decrease `paginate` config parameter to 2
3. Go to home page
4. Click "Next" pagination button
Page successfully opened.
"404 - Page not found" error occurred.
Because link looks like: `http://localhost/some/preffix/some/preffix/page/2/`.
As we can see, `/some/preffix/` part is duplicated here.
We can fix this bug just by getting rid of  `relLangURL` function call.
Original `.Paginator.Next.URL` already contains all the necessary language information.
:heavy_check_mark: English language, baseUrl with prefix
:heavy_check_mark: Russian language, baseUrl with prefix
:heavy_check_mark: English language, baseUrl without prefix
:heavy_check_mark: Russian language, baseUrl without …

Fixing pagination bug 

---

layouts/partials/post-info.html

Hi, @Mitrichius! Here is a bug that I found.
For now, all the categories links refers to `/category/` page.
You can see it here: https://deploy-preview-112--hugo-theme-anubis.netlify.app/
I fixed this bug using the same logic as for tag list ([see here](https://github.com/Mitrichius/hugo-theme-anubis/blob/master/layouts/partials/post-info.html#L26)).

Fixing wrong categories links below the post 

---

layouts/_default/taxonomy.html

Hi, @Mitrichius! Here is a bug that I found.
* Set up `baseURL` config parameter with some prefix (for example, `http://localhost/some/prefix/`)
* Go to one tag page (for example, "markdown" tag page - http://localhost:1313/some/prefix/tags/markdown/)
* Click "To all tags" button (screenshot with the placement of this button: https://s.mail.ru/fKhT/ZkCFccccm)
* All tags page successfully opened 
* Expected page url is `http://localhost:1313/some/prefix/tags`
* Unable to open all tags page (404 page not found)
* Actual page url is `http://localhost:1313/tags`
As you can see, there is no blog url prefix in the actual link.
Nice and easy, as always :)
Hugo-function [`relLangURL`](https://gohugo.io/functions/rellangurl) does exactly what we want to solve our problem.
We can just take this …

Fixing bug with wrong "goToAll" link on taxonomy page (tags, categories)

---

layouts/partials/language-switcher.html

Hi, @Mitrichius! The fourth pull-request from me during this long weekend :)
I'm not sure if it's a bug. Maybe we can categorise it as a user-experience issue. 
Anyway, I think I should share it with you.
For now, we have a language switcher at the bottom of the page (see [screenshot](https://s.mail.ru/uerQ/oWnczq5FB)).
This language switcher works this way: it always transfers the user to the home page (for selected language).
Imagine, we're currently on https://dmitrykolosov.ru/posts/ page.
As a user, I scrolled down to the bottom of the page and see "oh, the language switcher".
And I clicked on "English" it aaaaaaand ... I've transferred to the home page.
Is this what I expected? Not exactly. 
It would be better if I've been transferred to the same "/posts" page, but its English …

Fixing UX-issue with language-switcher

---

exampleSite/content/post/rich-content.md
exampleSiteMultilingual/content/post/rich-content.md
exampleSiteMultilingual/content/post/rich-content.pl.md

`WARN 2021/11/07 15:28:31 The "twitter_simple" shortcode will soon require two named parameters: user and id. See "/opt/build/repo/exampleSiteMultilingual/content/post/rich-content.md:26:1"`
...

Fix twitter warning

---

layouts/_default/baseof.html
layouts/partials/footer.html
layouts/partials/post-summary.html
layouts/partials/theme-switcher.html

I was trying to add emoji to some of the i18n text (e.g. light/dark theme selector), and I discovered that those emoji got stripped away when rendered.
After examining the template, it seems those i18n text got piped to the [humanize](https://gohugo.io/functions/humanize/) filter which are mainly to format non-user generated content (e.g. readable name from a url slug).
This PR removes the extra `humanize` filter, so emoji can be used.
---
My i18n override:
```yml
darkTheme:
other: "🌘"
lightTheme:
other: "☀️"
```

allow emoji to be used in i18n override

---

layouts/partials/post-info.html

fix for #132 
It seems to be easier than I thought, since there's only 2 places that concatenates categories / tags.

fix: use generated permalink from hugo

---

go.mod

* This will enable the theme to be imported as `hugo` module with a simple `module.imports` in the `config` file
* Removes the messy git submodule

Initialise `go` module

---

layouts/partials/theme-switcher.html

found theme switcher button text not changed after click, so I check the code,
seems changeButtonText does not need that local variable, and I made a small fix for myself.

fix: theme switcher not change button text

---

i18n/en.yaml
i18n/ru.yaml
layouts/partials/post-info.html

Based upon #183
Improvemtns:
- doesn't change default date format,
- doesn't ignore user's `dateFormat` preference,
- doesn't overwrite link to the post with `/arsip/`,
- has some i18n (sadly, only Russian and English),
- fixes the `<a/>` typo.
Non-improvements:
- still silently omits `lastMod` if it's not a valid date,
- still uses the cool `<time>` HTML tags.

`lastMod` support

---

assets/css/main.css
layouts/partials/head.html
layouts/partials/theme-switcher.html

When the `dark-without-switcher` or `light-without-switcher` style is selected, we don't need any of the JS code responsible for switching themes or restoring the opacity and visibility of the body (which is initially hidden, see #139), nor the CSS that actually hides it. We also don't need to have the contents of both `dark.css` & `light.css` embedded into `main.css`.
This is what the PR focuses on.

Cull excessive JS/CSS for `{dark,light}-without-swticher` styles

---

README.md
layouts/_default/list.html

To show full content on list pages for some sections. 
I use it for Notes section (there is for future Mastodon integration, notes < 1000 symbols without titles)

Add param sectionsWithFullContentOnListPage
