i18n/fr.yaml
here is a french translation for anubis theme
=> french translation

exampleSiteMultilingual/config.toml, exampleSiteMultilingual/content/_index.md, exampleSiteMultilingual/content/about.md, exampleSiteMultilingual/content/about.pl.md, exampleSiteMultilingual/content/archives.md, exampleSiteMultilingual/content/homepage/about.md, exampleSiteMultilingual/content/homepage/index.md, exampleSiteMultilingual/content/homepage/work.md, exampleSiteMultilingual/content/post/_index.md, exampleSiteMultilingual/content/post/_index.pl.md, exampleSiteMultilingual/content/post/emoji-support.md, exampleSiteMultilingual/content/post/emoji-support.pl.md, exampleSiteMultilingual/content/post/markdown-syntax.md, exampleSiteMultilingual/content/post/markdown-syntax.pl.md, exampleSiteMultilingual/content/post/math-typesetting.mmark, exampleSiteMultilingual/content/post/placeholder-text.md, exampleSiteMultilingual/content/post/placeholder-text.pl.md, exampleSiteMultilingual/content/post/rich-content.md, exampleSiteMultilingual/content/post/rich-content.pl.md, i18n/pl.yaml, layouts/_default/baseof.html, layouts/_default/terms.html, layouts/partials/articleInfoFull.html, layouts/partials/header.html, layouts/partials/languageSelect.html, layouts/partials/pagination.html, layouts/taxonomy/category.html, static/css/style.css
Hi @Mitrichius,
First of all, great work. I love the theme and use it for a personal website.
One thing that I miss is multilingual support. Let me know what you think about it.
=> Multilingual support

i18n/tw.yaml
=> Add zh-tw tw.yaml

i18n/de.yaml, layouts/partials/footer.html, layouts/partials/pagination.html, layouts/partials/postInfo.html, static/css/style.css
Fix wrong category links (issue #56)
=> some new features and bug fixes

assets/css/main.css, layouts/partials/head.html
It will allow to load a single file.
=> Merge customCSS inside main CSS

layouts/partials/social.html
=> allow non-standard urls (for telegram, etc) in social links

layouts/_default/list.html
=> Only show pages that are part of this list

layouts/_default/single.html, layouts/partials/disqus.html
This is a pull request for issue #103.
All the details are described inside the issue.
=> #103: extracting disqus code to separate file 

layouts/partials/head.html, layouts/partials/title.html
I want to be able to override `<title>` template in my blog, therefore I extracted it to a separate partial.
Nice and easy :)
=> Extracting <title> to be able to override it in the client code

layouts/partials/post-summary.html
Reverts Mitrichius/hugo-theme-anubis#105
=> Revert "Tweak theme to detect and use front matter "description" field"

README.md, assets/css/main.css, layouts/_default/single.html, layouts/partials/isso.html
This PR adds code for using [ISSO](https://posativ.org/isso/) as a comment system.
=> add isso comment to posts

i18n/pt.yaml
Hi there, thanks for the great theme :)
This PR only adds Portuguese translation.
=> add pt.yaml

layouts/partials/head.html, layouts/partials/theme-switcher.html
=> Remove flash for dark theme on loading

layouts/partials/head.html
=> Added support for meta keywords #137

layouts/404.html
Request add a Customer 404 Page, It can work fine if using GitHub Pages.
Please reference https://gohugo.io/templates/404/
Thanks
=> Add a Custom 404 Page

i18n/id.yaml
add id support (Bahasa Indonesia)
=> add id.yaml

assets/css/main.css
- Fixed top and right
- Cursor is now pointer when hovering similar to GitHub's
=> fix #156 improve copy code button

assets/css/main.css, layouts/partials/header.html, layouts/partials/mathjax_support.html
This PR enables rendering LaTeX equations through MathJax.
=> Add support for MathJax

README.md
* Update the portion about initialising as Hugo module
* Fix the link in `setup guide`
=> Update README.md installation section

README.md, layouts/partials/head.html, layouts/partials/umami_analytics.html
this brings support for Umami Analytics from https://umami.is
=> Support for Umami analytics

README.md, layouts/_default/single.html, layouts/partials/toc.html
Adds support for Hugo's auto-generated Tables of Contents.
=> Table of Contents

exampleSite/hugo.toml, layouts/partials/comments.html, layouts/partials/giscus.html
=> add Giscus support
